### ISSUE TITLE
overflow encountered in double_scalars

### ISSUE THREAD

**Issue by Yusnows** [gykovacs/smote_variants#11]
I use kmeans_SMOTE for the images mixing, but it occurs this issue, which showed below.

And I go to see the source code, I found that `avg_min_dist**len(X[0])/min_count` may be the cause. For an image, `len(X[0])` may be a vary large data.(I reshpe an image [1, 3, 380, 380] to [1, 433200], so len(X[0]) is 433200. As an exponent, it is really large.)

My question is: How to use this smote library for images mixing and avoid this issue?

![image](https://user-images.githubusercontent.com/25427848/66031334-c1440a80-e535-11e9-877c-a5860407dc79.png)

**Comment by gykovacs** [comment]
Interesting issue. I never thought of oversampling images like this. You are absolutely right, the line of code you mention will cause the overflow. 

However, the algorithm implemented follows the paper https://novaresearch.unl.pt/en/publications/improving-imbalanced-learning-through-a-heuristic-oversampling-me, thus, I consider this issue a limitation of the algorithm.

If you stick to use the kmean-smote, you could give a try to the implementation https://pypi.org/project/kmeans-smote/ or the other implementation in the ```imblearn``` package.

Alternatively, I would expect simpler SMOTE variants, like SMOTE and borderline-SMOTE work even on the very high dimensional set of images.

Also, I find it an interesting problem to oversample images like this, most importantly because the RGB color space that you use is not linear to perception. If you have a pixel which is eventually red, and the same pixel on the other image is green, you might get a blue pixel as the sample between them. For this operation to be meaningful, the images need to be highly standardized, having similar objects of similar color in the same location. If you could tell more about the problem, we could probably find better approaches than oversampling which is rarely used in the image domain.

**Comment by Yusnows** [comment]
Thank you for your reply.

My problem is imbalance image classification(multi classes). the instances of majority class are near 5 times to the minority class. So I want to generate more instances of the minority class. I have to 
admit that I am new to data science, I don't have a good idea to do this.

I will be especially grateful if you can give me some advice for this problem.

**Comment by gykovacs** [comment]
I think you have two options:
1) extract some features from the images, like intensity/color histograms, edge histograms, etc., thus reducing the dimensionality of images to feature vectors of a couple of tens or hundreds of elements. These vectors are comparable and can be fed into any classifier, and you can also carry out the oversampling of these vectors with any of the techniques implemented in the smote-variants package.
2) you can feed the images to deep convolutional neural networks which carry out the classification of the images. At some point in the network architecture, there will be layers of a couple of tens or hundreds of neurons. You can use the output of the network at this layer as a feature vector representation of the images, you can apply oversampling, and feed the results to any classifier.
3) there are problems, like building recognition, where images are classified by some keypoints. If your problem is such, you can extract invariant keypoints using SIFT or SURF and compare these keypoints to classify images.

**Comment by Yusnows** [comment]
Thank you very much.

I will take your advice to a try.
